### ISSUE TITLE
md5sums validation fail

### ISSUE THREAD

**Issue by dagodax** [KaOS-Community-Packages/qownnotes#1] opened 2016-05-12 13:27 UTC
I am trying to install this package from KCP but I  am getting stuck with a md5 validation error.

**Comment by Adurol** [comment] 2016-05-12 15:43
Confirmed. Looks like v15.05.9 got re-uploaded (with new MD5) after I pushed the update to KCP. Fixed with f0d55b6.

**Closed as completed by Adurol** 2016-05-12 15:43 UTC
